issues:
  exclude: [ ]
  exclude-case-sensitive: false
  exclude-use-default: false
  fix: true
  include: [ ]
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

linters-settings:
  dogsled:
    max-blank-identifiers: 2

  dupl:
    threshold: 100

  errcheck:
    check-blank: true
    check-type-assertions: true
    disable-default-exclusions: true
    exclude-functions: [ ]

  errchkjson:
    check-error-free-encoding: false
    report-no-exported: false

  exhaustive:
    check:
      - map
      - switch
    check-generated: true
    default-signifies-exhaustive: false
    explicit-exhaustive-map: false
    explicit-exhaustive-switch: false
    ignore-enum-members: ""
    ignore-enum-types: ""
    package-scope-only: false

  exhaustruct:
    exclude:
      - 'github\.com/rs/zerolog\.ConsoleWriter'
    include: [ ]

  forbidigo:
    analyze-types: true
    exclude-godoc-examples: true
    forbid:
      - ^(fmt\\.Print(|f|ln)|goto|print(|ln))$
      - ^(http\\.Default(Client|Transport))$
      - ^(time\\.Sleep)$
      - ^((==|!=) "")$

  funlen:
    lines: 60
    statements: 40

  gci:
    custom-order: false
    sections:
      - standard
      - default
      - prefix(github.com/LipsarHQ)
      - blank
      - dot
    skip-generated: true

  gocognit:
    min-complexity: 10

  goconst:
    ignore-calls: true
    ignore-tests: false
    match-constant: true
    max: 0
    min: 0
    min-len: 2
    min-occurrences: 2
    numbers: false

  gocritic:
    disabled-checks:
      - emptyStringTest
      - ruleguard
      - sloppyReassign
    enabled-checks:
      # Diagnostic.
      - appendAssign
      - argOrder
      - badCall
      - badCond
      - badLock
      - badRegexp
      - badSorting
      #      - badSyncOnceFunc # Not found.
      - builtinShadowDecl
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deferInLoop
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - dynamicFmtString
      - emptyDecl
      - evalOrder
      - exitAfterDefer
      - externalErrorReassign
      - filepathJoin
      - flagDeref
      - flagName
      - mapKey
      - nilValReturn
      - offBy1
      - regexpPattern
      - returnAfterHttpError
      #      - sloppyTestFuncName # Not found.
      - sloppyTypeAssert
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - syncMapLoadAndDelete
      - truncateCmp
      - uncheckedInlineErr
      - unnecessaryDefer
      - weakCond

      # Style.
      - assignOp
      - boolExprSimplify
      - builtinShadow
      - captLocal
      - commentFormatting
      - commentedOutImport
      - defaultCaseOrder
      - deferUnlambda
      - docStub
      - dupImport
      - elseif
      - emptyFallthrough
      #      - emptyStringTest # Don't use.
      - exposedSyncMutex
      - hexLiteral
      - httpNoBody
      - ifElseChain
      - importShadow
      - initClause
      - methodExprCall
      - nestingReduce
      - newDeref
      - octalLiteral
      - paramTypeCombine
      - preferFilepathJoin
      - ptrToRefParam
      - redundantSprint
      - regexpMust
      - regexpSimplify
      #      - ruleguard # Don't use.
      - singleCaseSwitch
      - sloppyLen
      - stringConcatSimplify
      - stringsCompare
      - switchTrue
      - timeCmpSimplify
      - timeExprSimplify
      #      - todoCommentWithoutDetail # Not found.
      - tooManyResultsChecker
      - typeAssertChain
      - typeDefFirst
      - typeSwitchVar
      - typeUnparen
      - underef
      - unlabelStmt
      - unlambda
      - unnamedResult
      - unnecessaryBlock
      - unslice
      - valSwap
      - whyNoLint
      - wrapperFunc
      - yodaStyleExpr

      # Performance.
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - preferDecodeRune
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - rangeExprCopy
      - rangeValCopy
      - sliceClear
      - stringXbytes
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      # - security
      - style
    settings:
      captLocal:
        paramsOnly: true
      elseif:
        skipBalanced: true
      hugeParam:
        sizeThreshold: 64
      ifElseChain:
        minThreshold: 2
      nestingReduce:
        bodyWidth: 2
      rangeExprCopy:
        sizeThreshold: 512
        skipTestFuncs: false
      rangeValCopy:
        sizeThreshold: 128
        skipTestFuncs: false
      tooManyResultsChecker:
        maxResults: 2
      truncateCmp:
        skipArchDependent: false
      underef:
        skipRecvDeref: false
      unnamedResult:
        checkExported: true

  godot:
    capital: false
    period: true
    scope: all

  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
      - OPTIMIZE
      - TODO

  gofumpt:
    extra-rules: true
    module-path: github.com/LipsarHQ

  gomnd:
    checks:
      - assign
      - argument
      - case
      - condition
      - operation
      - return
    ignored-files: [ ]
    ignored-functions: [ ]
    ignored-numbers: [ ]

  gomodguard:
    allowed:
      domains: [ ]
      modules:
        - github.com/go-resty/resty/v2
        - github.com/gorilla/schema
        - github.com/rs/zerolog
        - github.com/stretchr/testify
        - golang.org/x/time
    blocked:
      local_replace_directives: true
      modules:
        # Error.
        - github.com/pkg/errors:
            recommendations:
              - errors

        # Log.
        - github.com/sirupsen/logrus:
            recommendations:
              - github.com/rs/zerolog
        - go.uber.org/zap:
            recommendations:
              - github.com/rs/zerolog
        - log:
            recommendations:
              - github.com/rs/zerolog

        # Protocol Buffers.
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf

        # UUID.
        - github.com/gofrs/uuid:
            recommendations:
              - github.com/google/uuid
        - github.com/satori/go.uuid:
            recommendations:
              - github.com/google/uuid
      versions: []

  gosec:
    #    concurrency: 0
    confidence: low
    #    config: { }
    exclude-generated: false
    excludes: [ ]
    includes: [ ]
    severity: low

  gosimple:
    checks:
      - all

  grouper:
    # const.
    const-require-grouping: false
    const-require-single-const: false

    # import.
    import-require-grouping: true
    import-require-single-import: false

    # type.
    type-require-grouping: false
    type-require-single-type: false

    # var.
    var-require-grouping: false
    var-require-single-var: false

  govet:
    check-shadowing: true
    disable: [ ]
    disable-all: false
    enable: [ ]
    enable-all: true
  #    settings: { }

  importas:
    alias: [ ]
    no-extra-aliases: false
    no-unaliased: false

  lll:
    line-length: 120
    tab-width: 1

  makezero:
    always: false

  misspell:
    ignore-words: [ ]
    locale: US

  musttag:
    functions: [ ]

  nakedret:
    max-func-lines: 0

  nestif:
    min-complexity: 3

  nilnil:
    checked-types:
      - chan
      - func
      - iface
      - map
      - ptr

  nlreturn:
    block-size: 1

  nolintlint:
    allow-no-explanation: [ ]
    allow-unused: false
    require-explanation: true
    require-specific: true

  paralleltest:
    ignore-missing: false

  prealloc:
    for-loops: true
    range-loops: true
    simple: true

  predeclared:
    ignore: ""
    q: false

  promlinter:
    disabled-linters: [ ]
    strict: false

  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx

  staticcheck:
    checks:
      - all

  stylecheck:
    checks:
      - all
      - -ST1000

  tagalign:
    align: true
    order: [ ]
    sort: true
    strict: true

  tagliatelle:
    case:
      rules:
        bson: snake
        env: upperSnake
        json: snake
      use-field-name: false

  tenv:
    all: false

  testpackage:
    allow-packages:
      - main
    skip-regexp: (export|internal)_test\.go

  thelper:
    benchmark:
      begin: true
      first: true
      name: true
    fuzz:
      begin: true
      first: true
      name: true
    tb:
      begin: true
      first: true
      name: true
    test:
      begin: true
      first: true
      name: true

  unparam:
    check-exported: false

  usestdlibvars:
    constant-kind: true
    crypto-hash: true
    default-rpc-path: true
    http-method: true
    http-status-code: true
    sql-isolation-level: true
    time-layout: true
    time-month: true
    time-weekday: true
    tls-signature-scheme: true

  whitespace:
    multi-func: false
    multi-if: false

  wsl:
    allow-assign-and-anything: false
    allow-assign-and-call: true
    allow-cuddle-declarations: false
    allow-cuddle-with-calls:
      - Lock
      - RLock
    allow-cuddle-with-rhs:
      - Unlock
      - RUnlock
    allow-multiline-assign: true
    allow-separated-leading-comment: false
    allow-trailing-comment: false
    error-variable-names:
      - err
    force-case-trailing-whitespace: 0
    force-err-cuddling: false
    force-short-decl-cuddling: false
    strict-append: true

linters:
  disable:
    - depguard
    - dupword
    - ginkgolinter
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - gosmopolitan
    - ireturn
    - loggercheck
    - maintidx
    - nonamedreturns
    - reassign
    - revive
    - varnamelen
    - wrapcheck
  disable-all: false
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    #    - depguard # Don't use. Use "gomodguard" instead.
    - dogsled
    - dupl
    #    - dupword # Don't use.
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    #    - ginkgolinter # Don't use.
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    #    - gochecksumtype # Not found.
    - gocognit
    - goconst
    #    - gocyclo # Don't use.
    - godot
    - godox
    - goerr113
    #    - gofmt # Don't use.
    - gofumpt
    #    - goheader # Don't use.
    #    - goimports # Don't use. Use "gci" instead.
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    #    - gosmopolitan # Don't use.
    - grouper
    - govet
    - importas
    #    - inamedparam # Not found.
    - ineffassign
    - interfacebloat
    #    - ireturn # Don't use.
    - lll
    #    - loggercheck # Don't use.
    #    - maintidx # Don't use.
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    #    - nonamedreturns # Don't use.
    - nosprintfhostport
    - paralleltest
    #    - perfsprint # Not found.
    - prealloc
    - predeclared
    - promlinter
    #    - protogetter # Not found.
    #    - reassign # Don't use.
    #    - revive # TODO: ...
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    #    - testifylint # Not found.
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    #    - unused # Not found.
    - usestdlibvars
    #    - varnamelen # Don't use.
    - wastedassign
    - whitespace
    #    - wrapcheck # Don't use.
    - wsl
    - zerologlint

  enable-all: false
  fast: false
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

output:
  format: colored-line-number
  path-prefix: ""
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  uniq-by-line: true

run:
  allow-parallel-runners: false
  build-tags: [ ]
  issues-exit-code: 1
  modules-download-mode: readonly
  skip-dirs: [ ]
  skip-dirs-use-default: false
  skip-files: [ ]
  tests: true
  timeout: 1m

severity:
  case-sensitive: false
  default-severity: ""
  rules: [ ]